openapi: 3.0.1
info:
  description: Sekvensanalyseplatform
  title: SAP
  version: 0.1.0
servers:
  - url: 'http://localhost:8080/api/'
tags:
  - description: Operations about user
    name: user
  - description: Operations for isolates
    name: analysis

paths:
  /analysis:
    get:
      description: Page through all the analysis in the system (WIP)
      operationId: get_analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      tags:
        - analysis
      parameters:
        - name: paging_token
          in: query
          description: opaque token to supply to get the next page of isolates
          required: false
          schema:
            type: string
            format: byte
            nullable: true
        - name: page_size
          in: query
          required: false
          schema:
            type: number
            default: 100
      responses:
        '200':
          description: Page of isolates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAnalysis'

    post:
      description: Search all analysis by given query
      operationId: search_analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: query
      tags:
        - analysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisQuery'
      responses:
        '200':
          description: Page of isolates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAnalysis'


  /analysis/columns:
    get:
      description: Get column metadata, scoped to authenticated user
      operationId: get_columns
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      tags:
        - analysis
      responses:
        '200':
          description: Column collection
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Column'

  /analysis/changes:
    post:
      description: Submit a batch of analysis data changes
      operationId: submit_changes
      tags:
        - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisChange'
      responses:
        '200':
          description: Changes accepted 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisChange'

  /approvals:
    get:
      description: Retrieve list of approvals for authenticated user
      operationId: get_approvals
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      responses:
        '200':
          description: List of Approvals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Approval'
    post:
      description: Submit approval/rejection information
      operationId: create_approval
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApprovalRequest'
      responses:
        '201':
          description: Approval accepted 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approval'

  /approvals/matrix:
    get:
      description: Get the entire approval matrix for all analysis
      operationId: full_approval_matrix
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      responses:
        '200':
          description: Approval matrix 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApprovalMatrix"

  '/approvals/{approval_id}':
    delete:
      description: Cancel a pending approval
      operationId: cancel_approval
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      parameters:
        - name: approval_id
          in: path
          required: true
          schema:
            type: string
          description: Id of approval to cancel
          explode: true
      responses:
        '204':
          description: Approval cancelled successfully.
      
  /user/views:
    get:
      operationId: get_user_views
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDefinedView"
          description: Return user-defined view collection for the authenticated user
      tags:
        - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
    post:
      operationId: create_user_view
      requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDefinedView"
      responses:
        '204':
          description: "User-defined view created."
      tags:
        - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
  /user/views/{name}:
    delete:
      description: Delete an existing view
      operationId: delete_view
      tags:
        - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: Name of view to delete
      responses:
        '204':
          description: View deleted successfully.


components:
  schemas:
    Organization:
      type: string
      enum: [SSI, FVST]

    PageOfAnalysis:
      required:
        - paging_token
        - total_count
        - items
        - approval_matrix
      properties:
        paging_token:
          type: string
          nullable: true
          pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
        total_count:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/AnalysisResult'
        approval_matrix:
          $ref: '#/components/schemas/ApprovalMatrix'

    AnalysisQuery:
      properties:
        paging_token:
          type: string
          description: opaque token to supply to get the next page of isolates
          format: byte
          nullable: true
        page_size:
          type: integer
          default: 100
          nullable: true
        filters:
          type: object
          additionalProperties:
            type: string

    Column:
      properties:
        approvable:
          type: boolean
        editable:
          type: boolean
        pii:
          type: boolean
        organizations:
          type: array
          items:
            $ref: "#/components/schemas/Organization"
        field_name:
          type: string
        approves_with:
          type: array
          items:
            type: string

    UserDefinedView:
      type: object
      properties:
        name:
          type: string
        hidden_columns:
          type: array
          items:
            type: string
        column_resizing:
          type: object
          properties:
            column_widths:
              type: array
              items:
                type: object
                properties:
                  columnName:
                    type: string
                  width:
                    type: integer
            column_width:
              type: integer
        sort_by:
          type: array
          items:
            type: object
            properties:
              desc:
                type: boolean
              id:
                type: string
        column_order:
          type: array
          items:
            type: string
    ApprovalRequest:
      type: object
      required:
        - matrix
      properties:
        matrix:
          $ref: "#/components/schemas/ApprovalMatrix"

    Approval:
      allOf:
        - $ref: '#/components/schemas/ApprovalRequest'
        - type: object
          properties:
            id:
              type: string
            approver:
              type: string
            timestamp:
              type: string
              format: date-time
            status:
              type: string
              enum: [pending, cancelled, submitted]

    ApprovalStatus:
      type: string
      enum: [pending, rejected, approved]

    ApprovalMatrix:
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: string
          $ref: "#/components/schemas/ApprovalStatus"

    AnalysisChange:
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: string
    
    Resistance:
      type: string
      enum: ["Sensitiv", "Resistent", "Ukendt"]

    BaseMetadata:
      required:
        - isolate_id
        - sequence_id
        - sequence_filename
        - institution
        - received_date
        - run_id
        - provided_species
        - primary_isolate
      properties:
        isolate_id:
          type: string
        sequence_id:
          type: string
        sequence_filename:
          type: string
        institution:
          $ref: "#/components/schemas/Organization"
        project_number:
          type: number
        project_title:
          type: string
        sampling_date:
          format: date-time
          type: string
        received_date:
          format: date-time
          type: string
        run_id:
          type: string
        public:
          type: string
        provided_species:
          type: string
        primary_isolate:
          type: boolean


    TbrSpecificMetadata:
      type: object
      required:
        - run_date
      properties:
        cpr:
          type: string
          pattern: ^(?:(?:31(?:0[13578]|1[02])|(?:30|29)(?:0[13-9]|1[0-2])|(?:0[1-9]|1[0-9]|2[0-8])(?:0[1-9]|1[0-2]))[0-9]{2}\s?-?\s?[0-9]|290200\s-?\s[4-9]|2902(?:(?!00)[02468][048]|[13579][26])\s?-?\s?[0-3])[0-9]{3}|000000\s?-?\s?0000$ 
        gender:
          type: string
          enum:
            - M
            - K
        name:
          type: string
          x-faker: name.findName
        age:
          type: integer
          minimum: 0
          maximum: 128
        travel:
          type: string
        travel_country:
          type: string
          x-faker: address.country
        run_date:
          format: date-time
          type: string
        kma_received_date:
          format: date-time
          type: string
        kma:
          type: string
        region:
          type: string
        fud_number:
          type: string
        cluster_id:
          type: string
        epi_export:
          type: string

    TbrMetadata:
      allOf:
        - $ref: '#/components/schemas/BaseMetadata'
        - $ref: '#/components/schemas/TbrSpecificMetadata'

    LimsSpecificMetadata:
      type: object
      properties:
        chr_number:
          type: string
          pattern: \d{5,6}
        aut_number:
          type: string
        product_type:
          type: string
        product:
          type: string
        origin_country:
          type: string
          x-faker: address.country
        animal_species:
          type: string
        sample_info:
          type: string

    LimsMetadata:
      allOf:
        - $ref: '#/components/schemas/BaseMetadata'
        - $ref: '#/components/schemas/LimsSpecificMetadata'

    AnalysisResult:
      allOf:
        - $ref: '#/components/schemas/BaseMetadata'
        - $ref: '#/components/schemas/LimsSpecificMetadata'
        - $ref: '#/components/schemas/TbrSpecificMetadata'
        - type: object
          required:
            - _id
            - isolate_id
          properties:
            _id:
              type: string
              format: uuid
            resfinder_version:
              type: string
              pattern: ^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$ 
            QC_provided_species:
              type: number
            QC_genome1x:
              type: number
            QC_genome10x:
              type: number
            QC_Gsize_diff1x10:
              type: number
            QC_Avg_coverage:
              type: number
            QC_final:
              type: string
              enum: ["A", "B", "C"]
            subspecies:
              type: string
            species_final:
              type: string
            st:
              type: string
            pathotype:
              type: string
            pathotype_final:
              type: string
            serotype:
              type: string
            serotype_final:
              type: string
            adhesion:
              type: string
            toxins:
              type: string
            resistance_genes:
              type: string
            amr_profile:
              type: string
            amr_ami:
              $ref: "#/components/schemas/Resistance"
            amr_amp:
              $ref: "#/components/schemas/Resistance"
            amr_azi:
              $ref: "#/components/schemas/Resistance"
            amr_fep:
              $ref: "#/components/schemas/Resistance"
            amr_fot:
              $ref: "#/components/schemas/Resistance"
            amr_f_c:
              $ref: "#/components/schemas/Resistance"
            amr_fox:
              $ref: "#/components/schemas/Resistance"
            amr_taz:
              $ref: "#/components/schemas/Resistance"
            amr_t_c:
              $ref: "#/components/schemas/Resistance"
            amr_chl:
              $ref: "#/components/schemas/Resistance"
            amr_cip:
              $ref: "#/components/schemas/Resistance"
            amr_cli:
              $ref: "#/components/schemas/Resistance"
            amr_col:
              $ref: "#/components/schemas/Resistance"
            amr_dap:
              $ref: "#/components/schemas/Resistance"
            amr_etp:
              $ref: "#/components/schemas/Resistance"
            amr_ery:
              $ref: "#/components/schemas/Resistance"
            amr_fus:
              $ref: "#/components/schemas/Resistance"
            amr_gen:
              $ref: "#/components/schemas/Resistance"
            amr_imi:
              $ref: "#/components/schemas/Resistance"
            amr_kan:
              $ref: "#/components/schemas/Resistance"
            amr_lzd:
              $ref: "#/components/schemas/Resistance"
            amr_mero:
              $ref: "#/components/schemas/Resistance"
            amr_mup:
              $ref: "#/components/schemas/Resistance"
            amr_nal:
              $ref: "#/components/schemas/Resistance"
            amr_pen:
              $ref: "#/components/schemas/Resistance"
            amr_syn:
              $ref: "#/components/schemas/Resistance"
            amr_rif:
              $ref: "#/components/schemas/Resistance"
            amr_str:
              $ref: "#/components/schemas/Resistance"
            amr_sul:
              $ref: "#/components/schemas/Resistance"
            amr_tei:
              $ref: "#/components/schemas/Resistance"
            amr_trm:
              $ref: "#/components/schemas/Resistance"
            amr_tet:
              $ref: "#/components/schemas/Resistance"
            amr_tia:
              $ref: "#/components/schemas/Resistance"
            amr_tgc:
              $ref: "#/components/schemas/Resistance"
            amr_tmp:
              $ref: "#/components/schemas/Resistance"
            amr_van:
              $ref: "#/components/schemas/Resistance"

  securitySchemes:
    SAP_auth:
      scheme: bearer
      type: http
      x-bearerInfoFunc: openapi_server.controllers.security_controller_.info_from_SAP_auth
