openapi: 3.0.1
info:
  description: Sekvensanalyseplatform
  title: SAP
  version: 0.1.0
servers:
  - url: 'http://localhost:8080/api/'
tags:
  - description: Operations about user
    name: user
  - description: Operations for isolates
    name: analysis
security:
  - jwt: []

paths:
  /me:
    get:
      description: Describe the current user and their permissions
      operationId: who_am_i
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
      tags:
        - user
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: './user-info.v1.json'

  /analysis:
    get:
      description: Page through all the analysis in the system (WIP)
      operationId: get_analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      tags:
        - analysis
      parameters:
        - name: paging_token
          in: query
          description: opaque token to supply to get the next page of isolates
          required: false
          schema:
            type: string
            format: byte
            nullable: true
        - name: page_size
          in: query
          required: false
          schema:
            type: number
            default: 100
      responses:
        '200':
          description: Page of isolates
          content:
            application/json:
              schema:
                $ref: './page-of-analysis.v1.json'

    post:
      description: Search all analysis by given query
      operationId: search_analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: query
      tags:
        - analysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: './analysis-query.v1.json'
      responses:
        '200':
          description: Page of isolates
          content:
            application/json:
              schema:
                $ref: './page-of-analysis.v1.json'
  /analysis/columns:
    get:
      description: Get column metadata, scoped to authenticated user
      operationId: get_columns
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      tags:
        - analysis
      responses:
        '200':
          description: Column collection
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './column.v1.json'
  /analysis/changes:
    post:
      description: Submit a batch of analysis data changes
      operationId: submit_changes
      tags:
        - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              $ref: './analysis-change.v1.json'
      responses:
        '200':
          description: Changes accepted 
          content:
            application/json:
              schema:
                $ref: './analysis-change.v1.json'
  /analysis/reload_metadata:
    post:
      description: Reload metadata for a given isolate
      operationId: reload_metadata
      tags:
        - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              $ref: './metadata-reload-request.v1.json'
      responses:
        '200':
          description: Reload successful 
          content:
            application/json:
              schema:
                $ref: './metadata-reload-response.v1.json'

  /approvals:
    get:
      description: Retrieve list of approvals for authenticated user
      operationId: get_approvals
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      responses:
        '200':
          description: List of Approvals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './approval.v1.json'
    post:
      description: Submit approval/rejection information
      operationId: create_approval
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              $ref: './approval-request.v1.json'
      responses:
        '201':
          description: Approval accepted 
          content:
            application/json:
              schema:
                $ref: './approval.v1.json'
  /approvals/matrix:
    get:
      description: Get the entire approval matrix for all analysis
      operationId: full_approval_matrix
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      responses:
        '200':
          description: Approval matrix 
          content:
            application/json:
              schema:
                $ref: "./approval-matrix.v1.json"
  '/approvals/{approval_id}':
    delete:
      description: Cancel a pending approval
      operationId: cancel_approval
      tags:
        - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      parameters:
        - name: approval_id
          in: path
          required: true
          schema:
            type: string
          description: Id of approval to cancel
          explode: true
      responses:
        '204':
          description: Approval cancelled successfully.
      
  /user/views:
    get:
      operationId: get_user_views
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./user-defined-view.v1.json"
          description: Return user-defined view collection for the authenticated user
      tags:
        - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
    post:
      operationId: create_user_view
      requestBody:
          content:
            application/json:
              schema:
                $ref: "./user-defined-view.v1.json"
      responses:
        '204':
          description: "User-defined view created."
      tags:
        - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
  /user/views/{name}:
    delete:
      description: Delete an existing view
      operationId: delete_view
      tags:
        - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: Name of view to delete
      responses:
        '204':
          description: View deleted successfully.

  /gdpr/extract:
    get:
      description: Extract all data given a personal identifier
      operationId: extract_data_from_pi
      tags:
        - gdpr
      x-openapi-router-controller: web.src.SAP.generated.controllers.gdpr_controller
      parameters:
        - in: query
          name: identifier_type
          schema:
            $ref: './personal-identifier-type.v1.json'
          description: Identifier type
          required: true
        - in: query
          name: identifier
          schema:
            type: string
          description: Personal identifier number.
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './personal-data.v1.json'
  /gdpr/forget:
    get:
      description: Forget about a person identifer, GDPR right to be forgotten
      operationId: forget_pii
      tags:
        - gdpr
      x-openapi-router-controller: web.src.SAP.generated.controllers.gdpr_controller
      parameters:
        - in: query
          name: identifier_type
          schema:
            $ref: './personal-identifier-type.v1.json'
          description: Identifier type
          required: true
        - in: query
          name: identifier
          schema:
            type: string
          description: Personal identifier number.
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './personal-data.v1.json'

  /upload/single_upload:
    post:
      description: Manually upload isolate with metadata
      operationId: single_upload
      x-openapi-router-controller: web.src.SAP.generated.controllers.upload_controller
      x-codegen-request-body-name: query
      tags:
        - upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: './single-upload-request.v1.json'
            encoding:
              metadata:
                contentType: application/json
              file:
                contentType: application/gzip
      responses:
        '200':
          description: Isolate uploaded successfully. Reports errors.
          content:
            application/json:
              schema:
                $ref: './upload-response.v1.json'

  /upload/multi_upload:
    post:
      description: Manually upload multiple sequences with metadata
      operationId: multi_upload
      x-openapi-router-controller: web.src.SAP.generated.controllers.upload_controller
      x-codegen-request-body-name: query
      tags:
        - upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: './multi-upload-request.v1.json'
            encoding:
              metadata_tsv:
                contentType: text/tsv
              files:
                contentType: application/gzip
      responses:
        '200':
          description: Isolate uploaded successfully. Reports errors.
          content:
            application/json:
              schema:
                $ref: './upload-response.v1.json'

  /upload/bulk_metadata:
    post:
      description: Manually upload metadata for previously uploaded sequence files
      operationId: bulk_metadata
      x-openapi-router-controller: web.src.SAP.generated.controllers.upload_controller
      x-codegen-request-body-name: query
      tags:
        - upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: './bulk-upload-request.v1.json'
            encoding:
              path:
                contentType: text/plain
              metadata_tsv:
                contentType: text/tsv
      responses:
        '200':
          description: Isolate uploaded successfully. Reports errors.
          content:
            application/json:
              schema:
                $ref: './upload-response.v1.json'
components:
  schemas: {}
    
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: web.src.SAP.generated.controllers.security_controller_.info_from_jwt
