repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/necaris/pre-commit-pyright
    rev: '1.1.53'
    hooks:
      - id: pyright