trigger:
   - '*'
# Configure BuildNumber
name: $(Rev:r)

stages:
  - stage: Build
    jobs:
      - job: Build_api
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        dependsOn: []

        variables:
          imageName: '$(dockerId)/sap-api:$(Build.BuildNumber)'
          imageNameRelease: '$(dockerId)/sap-api:latest'

        steps:
        - script: DOCKER_BUILDKIT=0 docker build -f Dockerfile -t $(imageName) .
          displayName: 'Docker build and test'
          workingDirectory: web

        - script: |
            export id=$(docker images --filter "label=test=true" -q | head -1)
            docker create --name testapi $id
            docker cp testapi:/app/junit.xml ./junit.xml
            docker rm testapi
          displayName: 'Get test results'
          condition: succeededOrFailed()

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '**/junit.xml' 
            searchFolder: '$(System.DefaultWorkingDirectory)/'
            publishRunAttachments: true
            failTaskOnFailedTests: true
          displayName: 'Publish test results'
          condition: succeededOrFailed()

        - script: |
            echo $MAPPED_DOCKER_PASS | docker login -u $(dockerId) --password-stdin
            docker push $(imageName)
            docker tag $(imageName) $(imageNameRelease)
            docker push $(imageNameRelease)
          displayName: 'Publish docker image'
          env:
            MAPPED_DOCKER_PASS: $(dockerPass)

      - job: Build_webapp
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        dependsOn: []

        variables:
          imageName: '$(dockerId)/sap-web:$(Build.BuildNumber)'
          imageNameRelease: '$(dockerId)/sap-web:latest'

        steps:
        - script: DOCKER_BUILDKIT=0 docker build -f Dockerfile -t $(imageName) .
          displayName: 'Docker build and test'
          workingDirectory: app

        - script: |
            export id=$(docker images --filter "label=test=true" -q | head -1)
            docker create --name testweb $id
            docker cp testweb:/app/junit.xml ./junit.xml
            docker rm testweb
          displayName: 'Get test results'
          condition: succeededOrFailed()

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '**/junit.xml' 
            searchFolder: '$(System.DefaultWorkingDirectory)/'
            publishRunAttachments: true
            failTaskOnFailedTests: true
          displayName: 'Publish test results'
          condition: succeededOrFailed()

        - script: |
            echo $MAPPED_DOCKER_PASS | docker login -u $(dockerId) --password-stdin
            docker push $(imageName)
            docker tag $(imageName) $(imageNameRelease)
            docker push $(imageNameRelease)
          displayName: 'Publish docker image'
          env:
            MAPPED_DOCKER_PASS: $(dockerPass)

      - job: Build_listener
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        dependsOn: []

        variables:
          listenerImageName: '$(dockerId)/bifrost-listener:$(Build.BuildNumber)'
          listenerImageNameRelease: '$(dockerId)/bifrost-listener:latest'

        steps:
        - script: DOCKER_BUILDKIT=0 docker build -f ./bifrost_listener/Dockerfile -t $(listenerImageName) ./bifrost_listener
          displayName: 'Docker build and test listener'
          workingDirectory: bifrost

        - script: |
            echo $MAPPED_DOCKER_PASS | docker login -u $(dockerId) --password-stdin
            docker push $(listenerImageName)
            docker tag $(listenerImageName) $(listenerImageNameRelease)
            docker push $(listenerImageNameRelease)
          displayName: 'Publish docker images'
          env:
            MAPPED_DOCKER_PASS: $(dockerPass)

      - job: Build_broker
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        dependsOn: []

        variables:
          brokerImageName: '$(dockerId)/sap-queue-broker:$(Build.BuildNumber)'
          brokerImageNameRelease: '$(dockerId)/sap-queue-broker:latest'

        steps:
        - script: DOCKER_BUILDKIT=0 docker build -f ./bifrost_queue_broker/Dockerfile -t $(brokerImageName) ./bifrost_queue_broker
          displayName: 'Docker build and test broker'
          workingDirectory: bifrost

        - script: |
            export id=$(docker images --filter "label=test=true" -q | head -1)
            docker create --name testbroker $id
            docker cp testbroker:/app/junit.xml ./junit.xml
            docker rm testbroker
          displayName: 'Get test results'
          condition: succeededOrFailed()

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '**/junit.xml' 
            searchFolder: '$(System.DefaultWorkingDirectory)/'
            publishRunAttachments: true
            failTaskOnFailedTests: true
          displayName: 'Publish test results'
          condition: succeededOrFailed()

        - script: |
            echo $MAPPED_DOCKER_PASS | docker login -u $(dockerId) --password-stdin
            docker push $(brokerImageName)
            docker tag $(brokerImageName) $(brokerImageNameRelease)
            docker push $(brokeImageNameRelease)
            docker push $(brokerImageName)
          displayName: 'Publish docker images'
          env:
            MAPPED_DOCKER_PASS: $(dockerPass)

      - job: Build_auth
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        dependsOn: []
        variables:
          imageName: '$(dockerId)/auth-selfservice-ui:$(Build.BuildNumber)'
          imageNameRelease: '$(dockerId)/auth-selfservice-ui:latest'

        steps:
        - script: DOCKER_BUILDKIT=0 docker build -f Dockerfile -t $(imageName) .
          displayName: 'Docker build and test'
          workingDirectory: auth

        - script: |
            echo $MAPPED_DOCKER_PASS | docker login -u $(dockerId) --password-stdin
            docker push $(imageName)
            docker tag $(imageName) $(imageNameRelease)
            docker push $(imageNameRelease)

          displayName: 'Publish docker image'
          env:
            MAPPED_DOCKER_PASS: $(dockerPass)

      - job: Prep_artifact
        pool:
          vmImage: 'ubuntu-latest'
        continueOnError: false
        variables:
          buildNo: '$(Build.BuildNumber)'

        steps:
        - script: |
            echo $(buildNo) >> tag.txt
          displayName: 'Stamp build number'
          workingDirectory: $(Build.ArtifactStagingDirectory)

        - task: CopyFiles@2
          inputs:
            contents: |
              Makefile
              docker-compose.yml
              docker-compose.live.yml
              Caddyfile
              sofi.service
              sofi_filesync.service
              sofi_filesync.sh
              auth/config/**
              auth/pg/pg-init/**
              management_scripts/**
            targetFolder: $(build.artifactstagingdirectory)
          displayName: 'Copy deployment artifacts into staging folder'

        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
            artifactName: 'drop' 
            publishLocation: 'Container'
          displayName: 'Publish build artifact'


  - stage: Deploy_Test
    pool: 
      name: Computerome
      demands:
        - agent.name -equals foodwebdev
    jobs:
    - deployment: deploy_test
      continueOnError: false
      environment: SOFI Test

      strategy:
        runOnce:
          deploy:
            steps:
              - download: none

              - task: DownloadPipelineArtifact@2
                displayName: "Download build artifact"
                inputs:
                  artifactName: drop
                  targetPath: $(System.DefaultWorkingDirectory)
              
              - script: |
                  cp -R ./* /opt/sofi/
                  cd /opt/sofi/
                  sed -i "s/^SOFI_RELEASE_TAG=.*$/SOFI_RELEASE_TAG=`cat tag.txt`/g" .env
                  chmod -R +x /opt/sofi/management_scripts
                  chmod +x /opt/sofi/sofi_filesync.sh
                  chmod +x /opt/sofi/container_restart.sh
                  systemctl disable sofi_filesync.service
                  systemctl disable container_restart.service
                  systemctl disable container_restart.timer
                  cp /opt/sofi/sofi_filesync.service /etc/systemd/system/sofi_filesync.service
                  cp /opt/sofi/container_restart.service /etc/systemd/system/container_restart.service
                  cp /opt/sofi/container_restart.timer /etc/systemd/system/container_restart.timer
                  systemctl enable sofi_filesync.service
                  systemctl enable container_restart.service
                  systemctl enable container_restart.timer
                  systemctl disable sofi.service
                  make install
                  systemctl restart sofi.service

  - stage: Deploy_Prod
    pool: 
      name: Computerome
      demands:
        - agent.name -equals foodweb
    jobs:
    - deployment: deploy_prod
      continueOnError: false
      environment: SOFI Prod

      strategy:
        runOnce:
          deploy:
            steps:
              - download: none

              - task: DownloadPipelineArtifact@2
                displayName: "Download build artifact"
                inputs:
                  artifactName: drop
                  targetPath: $(System.DefaultWorkingDirectory)
              
              - script: |
                  cp -R ./* /opt/sofi/
                  cd /opt/sofi/
                  sed -i "s/^SOFI_RELEASE_TAG=.*$/SOFI_RELEASE_TAG=`cat tag.txt`/g" .env
                  chmod -R +x /opt/sofi/management_scripts
                  chmod +x /opt/sofi/sofi_filesync.sh
                  #systemctl disable sofi_filesync.service
                  cp /opt/sofi/sofi_filesync.service /etc/systemd/system/sofi_filesync.service
                  #systemctl enable sofi_filesync.service
                  systemctl disable sofi.service
                  make install
                  systemctl restart sofi.service

