version: "3.4"

x-extra_hosts:
  &default-extra_hosts
  - "sofi_tbr_integration:192.168.113.11"

services:
  sap_app:
    image: sekvensanalyseplatform/sap-web:${SOFI_RELEASE_TAG}

  sap_api:
    image: sekvensanalyseplatform/sap-api:${SOFI_RELEASE_TAG}
    logging:
      driver: local
      options:
        max-size: 50m
        max-file: "20"

  sap_broker_queue:
    image: sekvensanalyseplatform/sap-queue-broker:${SOFI_RELEASE_TAG}
    extra_hosts: *default-extra_hosts

  bifrost_listener:
    image: sekvensanalyseplatform/bifrost-listener:${SOFI_RELEASE_TAG}
    extra_hosts: *default-extra_hosts

  auth-selfservice-ui:
    image: sekvensanalyseplatform/auth-selfservice-ui:${SOFI_RELEASE_TAG}

  kratos:
    logging:
      driver: local
      options:
        max-size: 50m
        max-file: "20"

