version: "3.4"
services:
  sap_api:
    build:
      context: ./web
      target: final
    environment:
      # don't litter host with pyc files; we always want latest state from file
      - PYTHONDONTWRITEBYTECODE=1
    user: ${CURRENT_UID}
    volumes:
      # Change path before : to point to local web.
      - ./web:/app/web:ro
    depends_on:
      - "bifrost_db"

  sap_broker_queue:
    image: sekvensanalyseplatform/sap-queue-broker:437
    depends_on:
      - "sap_api"
      - "bifrost_db"

  bifrost_listener:
    build:
      context: ./bifrost/bifrost_listener
      dockerfile: Dockerfile
    depends_on:
      - "bifrost_db"

  sap_app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    user: ${CURRENT_UID}
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app:rw
    stdin_open: true

  mocks:
    image: caddy
    volumes:
      - ./openapi_specs/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "4099:4099"
    depends_on:
      - lims_mock

  lims_mock:
    container_name: lims_integration
    image: stoplight/prism:latest
    ports:
      - "4021:4021"
    command: mock /openapi_specs/lims.v1.yaml -h 0.0.0.0 -p 4021
    volumes:
      - ./openapi_specs:/openapi_specs

  tbr_integration:
    container_name: tbr_integration
    build: ./sap_tbr_integration
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
      - "5001:443"

  bifrost_db:
    image: mongo:4.4.2
    command: --replSet rs0
    container_name: bifrost_db
    restart: always
    user: ${CURRENT_UID}
    environment:
      MONGO_INITDB_DATABASE: bifrost_test
    volumes:
      - ./bifrost/bifrost_db/initdb.d/:/docker-entrypoint-initdb.d/
      - ./bifrost/bifrost_db/data/db/:/data/db/
      - ./bifrost/bifrost_db/data/log/:/var/log/mongodb/
    ports:
      - "27017:27017"
    expose:
      - 27017
    extra_hosts:
      - "bifrost_db:127.0.0.1"
    healthcheck:
      # causes replicaset to initialize as a side effect
      test: 'test $$(mongo bifrost_test --eval "rs.status().ok" --quiet) -eq 1 -a $$(mongo bifrost_test --eval "rs.status().set" --quiet) = rs0'
      interval: 60s
      start_period: 15s

  # Allows for testing email-based self-service flows in kratos (forgot password, account verification, etc)
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
