version: '3'
services:
  mongo_seeding:
    build: ./seed_data/
    depends_on:
      - mongo
  sap_api:
    volumes:
        # Change path before : to point to local web.
        - ./web:/app/web
    command: ["/bin/sh", "-c", "/app/start.sh"]
