version: '3'
services:
  sap_api:
    build: .
    ports:
      - "8080:80"
    environment:
      -  APP_MODULE=wsgi:app
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"