version: "3.4"

x-extra_hosts:
  &default-extra_hosts
  - "sofi_tbr_integration:192.168.113.11"

services:
  sap_app:
    image: sekvensanalyseplatform/sap-web:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sap_api:
    image: sekvensanalyseplatform/sap-api:latest
    logging:
      driver: local
      options:
        max-size: 50m
        max-file: "20"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sap_broker_queue:
    image: sekvensanalyseplatform/bifrost-queue-broker:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    extra_hosts: *default-extra_hosts

  bifrost_listener:
    image: sekvensanalyseplatform/bifrost-listener:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    extra_hosts: *default-extra_hosts

  auth-selfservice-ui:
    image: sekvensanalyseplatform/auth-selfservice-ui:master
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --interval 30

  kratos:
    logging:
      driver: local
      options:
        max-size: 50m
        max-file: "20"

