version: '3.4'
services:
  sap_api:
    environment:
    # don't litter host with pyc files; we always want latest state from file
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
    # Change path before : to point to local web.
      - ./web:/app/web:ro
    ports:
      - "6000:6000"
    depends_on:
      - "bifrost_db"
    command: ["/bin/sh", "-c", "/app/start.sh"]


  sap_app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app:rw
    stdin_open: true

  mocks:
    image: caddy
    volumes:
      - ./openapi_specs/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '4099:4099'
    depends_on:
      - lims_mock
      - sap_mock
  lims_mock:
    image: stoplight/prism:latest
    command: mock /openapi_specs/lims.v1.yaml -h 0.0.0.0 -p 4021
    volumes:
      - ./openapi_specs:/openapi_specs
  sap_mock:
    image: stoplight/prism:latest
    command: mock /openapi_specs/SAP/SAP.yaml -h 0.0.0.0 -p 4011
    volumes:
      - ./openapi_specs:/openapi_specs
  
  tbr_integration:
    build: ./sap_tbr_integration
    ports:
      - '5000:80'
      - '5001:443'


  bifrost_db:
    build: bifrost/bifrost_db
    expose:
      - 27017
    ports:
      - "27017:27017"
    extra_hosts:
      bifrost_db: 127.0.0.1
