version: '3'
services:
  mongo_seeding:
    build: ./seed_data/
    depends_on:
      - mongo
  dashboard:
    volumes:
        # Change path before : to point to local web. ./web might work.
        - /c/Users/asa/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/ahmad/SAP/web:/app/web
    command: ["/bin/sh", "-c", "/app/start.sh"]
