version: '3.8'
services:
  sap_api:
    build: 
      context: .
      target: final
    expose:
      - 6000
    environment:
      - APP_MODULE=wsgi:app
    depends_on:
      - "bifrost_db"

  sap_app:
    build:
      context: ./app
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    depends_on:
      - "sap_api"

  proxy:
    image: caddy:2.2.0-alpine
    ports:
      - "8080:80"
      - "8081:443"
    command:
      - "caddy"
      - "run"
      - "-config"
      - "/etc/Caddyfile"
    depends_on:
      -  "sap_api"
      -  "sap_app"
    volumes:
        - ./Caddyfile:/etc/Caddyfile

  bifrost_db:
    build: bifrost_db
    expose:
      - 27017
    ports:
      - "27017:27017"
