version: '3'
services:
  mongo_seeding:
    build: ./seed_data/
    depends_on:
      - mongo
  sap_api:
    volumes:
        # Change path before : to point to local web.
        - ./web:/app/web
    command: ["/bin/sh", "-c", "/app/start.sh"]
  mocks:
    image: caddy
    volumes:
      - ./openapi-specs/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '4010:80'
    depends_on:
      - lims_mock
  lims_mock:
    image: stoplight/prism:latest
    command: mock /openapi-specs/lims.v1.yaml -h 0.0.0.0
    volumes:
      - ./openapi-specs:/openapi-specs
