pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: '$(dockerId)/auth-selfservice-ui:$(Build.SourceBranchName)'
  imageNameRelease: '$(dockerId)/auth-selfservice-ui:latest'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build and test'
  workingDirectory: app

- script: |
    docker login -u $(dockerId) -p $(dockerPass)
    docker push $(imageName)
  displayName: 'Publish docker image'

- script: |
    echo 'docker login -u $(dockerId) -p $(dockerPass)' > deployment.sh
    echo 'docker pull $(imageName)' >> deployment.sh
    echo 'docker tag $(imageName) $(imageNameRelease)' >> deployment.sh
    echo 'docker push $(imageNameRelease)' >> deployment.sh
  displayName: 'Create deployment script'

- publish: deployment.sh
  artifact: WEB_DEPLOYMENT