pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: '$(dockerId)/auth-selfservice-ui:$(Build.SourceBranchName)'
  imageNameRelease: '$(dockerId)/auth-selfservice-ui:latest'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build and test'
  workingDirectory: auth

- script: |
    echo $MAPPED_DOCKER_PASS | docker login -u $(dockerId) --password-stdin
    docker push $(imageName)
  displayName: 'Publish docker image'
  env:
    MAPPED_DOCKER_PASS: $(dockerPass)

- script: |
    echo 'echo $MAPPED_DOCKER_PASS | docker login -u $(dockerId) --password-stdin' > deployment.sh
    echo 'docker pull $(imageName)' >> deployment.sh
    echo 'docker tag $(imageName) $(imageNameRelease)' >> deployment.sh
    echo 'docker push $(imageNameRelease)' >> deployment.sh
  displayName: 'Create deployment script'

- publish: deployment.sh
  artifact: WEB_DEPLOYMENT