openapi: 3.0.1
info:
  description: Sekvensanalyseplatform
  title: SAP
  version: 0.1.0
servers:
- url: http://localhost:8080/api/
tags:
- description: Operations about user
  name: user
- description: Operations for isolates
  name: analysis
paths:
  /analysis:
    get:
      description: Page through all the analysis in the system (WIP)
      operationId: get_analysis
      parameters:
      - description: opaque token to supply to get the next page of isolates
        explode: true
        in: query
        name: pagingToken
        required: false
        schema:
          format: byte
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: pageSize
        required: false
        schema:
          default: 100
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAnalysis'
          description: Page of isolates
      tags:
      - analysis
      x-openapi-router-controller: web.SAP.generated.controllers.analysis_controller
  /user:
    post:
      description: This can only be done by the logged in user.
      operationId: create_user
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
        required: true
      responses:
        default:
          content: {}
          description: successful operation
      summary: Create user
      tags:
      - user
      x-codegen-request-body-name: body
      x-openapi-router-controller: web.SAP.generated.controllers.user_controller
  /user/login:
    get:
      operationId: login_user
      parameters:
      - description: The user name for login
        explode: true
        in: query
        name: username
        required: true
        schema:
          type: string
        style: form
      - description: The password for login in clear text
        explode: true
        in: query
        name: password
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: successful operation
          headers:
            X-Expires-After:
              description: date in UTC when token expires
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          content: {}
          description: Invalid username/password supplied
      summary: Logs user into the system
      tags:
      - user
      x-openapi-router-controller: web.SAP.generated.controllers.user_controller
  /user/logout:
    get:
      operationId: logout_user
      responses:
        default:
          content: {}
          description: successful operation
      summary: Logs out current logged in user session
      tags:
      - user
      x-openapi-router-controller: web.SAP.generated.controllers.user_controller
  /user/{username}:
    delete:
      description: This can only be done by the logged in user.
      operationId: delete_user
      parameters:
      - description: The name that needs to be deleted
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content: {}
          description: Invalid username supplied
        "404":
          content: {}
          description: User not found
      summary: Delete user
      tags:
      - user
      x-openapi-router-controller: web.SAP.generated.controllers.user_controller
    get:
      operationId: get_user_by_name
      parameters:
      - description: 'The name that needs to be fetched. Use user1 for testing. '
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: successful operation
        "400":
          content: {}
          description: Invalid username supplied
        "404":
          content: {}
          description: User not found
      summary: Get user by user name
      tags:
      - user
      x-openapi-router-controller: web.SAP.generated.controllers.user_controller
    put:
      description: This can only be done by the logged in user.
      operationId: update_user
      parameters:
      - description: name that need to be updated
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        description: Updated user object
        required: true
      responses:
        "400":
          content: {}
          description: Invalid user supplied
        "404":
          content: {}
          description: User not found
      summary: Updated user
      tags:
      - user
      x-codegen-request-body-name: body
      x-openapi-router-controller: web.SAP.generated.controllers.user_controller
components:
  schemas:
    Analysis:
      example:
        testTimestamp: 2000-01-23T04:56:07.000+00:00
        isolateId: 1231_14_XDR
        agent: e.coli
        approved: true
        resfinderVersion: "1.99"
        species: rat
        dateReceived: 2000-01-23
        organization: FVST
        analysisId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        project: project
        serumType: XXXYYAAA
      properties:
        analysisId:
          format: uuid
          type: string
        isolateId:
          example: 1231_14_XDR
          pattern: ^\d{4}_\d{2}_[A-Z0-9]{3}$
          type: string
        testTimestamp:
          format: date-time
          type: string
        dateReceived:
          format: date
          type: string
        resfinderVersion:
          example: "1.99"
          pattern: ^\d*\.\d*$
          type: string
        serumType:
          example: XXXYYAAA
          pattern: ^[A-Z]{8}$
          type: string
        agent:
          enum:
          - e.coli
          - salmonella
          type: string
        species:
          enum:
          - rat
          - human
          - pig
          - dog
          type: string
        organization:
          enum:
          - FVST
          - SSI
          type: string
        project:
          type: string
        approved:
          type: boolean
      required:
      - analysisId
      - approved
      - dateReceived
      - isolateId
      - testTimestamp
    PageOfAnalysis:
      example:
        pagingToken: pagingToken
        totalCount: 0.8008281904610115
        items:
        - testTimestamp: 2000-01-23T04:56:07.000+00:00
          isolateId: 1231_14_XDR
          agent: e.coli
          approved: true
          resfinderVersion: "1.99"
          species: rat
          dateReceived: 2000-01-23
          organization: FVST
          analysisId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          project: project
          serumType: XXXYYAAA
        - testTimestamp: 2000-01-23T04:56:07.000+00:00
          isolateId: 1231_14_XDR
          agent: e.coli
          approved: true
          resfinderVersion: "1.99"
          species: rat
          dateReceived: 2000-01-23
          organization: FVST
          analysisId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          project: project
          serumType: XXXYYAAA
      properties:
        pagingToken:
          nullable: true
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
        totalCount:
          type: number
        items:
          items:
            $ref: '#/components/schemas/Analysis'
          type: array
      required:
      - items
      - pagingToken
      - totalCount
    User:
      example:
        firstName: firstName
        lastName: lastName
        password: password
        userStatus: 6
        phone: phone
        id: 0
        email: email
        username: username
      properties:
        id:
          format: int64
          type: integer
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          description: User Status
          format: int32
          type: integer
      type: object
  securitySchemes:
    SAP_auth:
      scheme: bearer
      type: http
      x-bearerInfoFunc: openapi_server.controllers.security_controller_.info_from_SAP_auth
